version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      bundler-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directories:
      - /cmd/cue2openapi
      - /cmd/openapi2md
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      gomod-minor-patch:
        update-types:
          - minor
          - patch
