lintcue:
	@echo "  >  Linting CUE schema ..."
	@cue vet ./schema.cue --all-errors --verbose

lintyml:
	@echo "  >  Linting YAML files ..."
	@echo "  >  Linting .github/security-insights.yml ..."
	@cue vet -d '#SecurityInsights' ./schema.cue .github/security-insights.yml
	@echo "  >  Linting template-full.yml ..."
	cue vet -d '#SecurityInsights' ./schema.cue examples/example-full.yml
	@echo "  >  Linting template-minimum.yml ..."
	cue vet -d '#SecurityInsights' ./schema.cue examples/example-minimum.yml
	@echo "  >  Linting template-multi-repository-project-reuse.yml ..."
	cue vet -d '#SecurityInsights' ./schema.cue examples/example-multi-repository-project-reuse.yml
	@echo "  >  Linting template-multi-repository-project.yml ..."
	cue vet -d '#SecurityInsights' ./schema.cue examples/example-multi-repository-project.yml

cuegen:
	@echo "  >  Generating types from cue schema ..."
	@cue exp gengotypes schema.cue
	@echo "  >  vet the generated go types ..."
	@go vet cue_types_gen.go

genopenapi:
	@echo "  >  Converting CUE schema to OpenAPI ..."
	@cd cmd/cue2openapi && go run . -schema ../../schema.cue -output ../../openapi.yaml
	@echo "  >  OpenAPI schema generation complete!"

genindex:
	@echo "  >  Copying README.md to docs/index.md for website ..."
	@{ \
		echo "---"; \
		echo "layout: default"; \
		echo "title: Home"; \
		echo "nav-title: About"; \
		echo "note: This file is automatically generated from README.md. Do not edit this file directly."; \
		echo "---"; \
		echo ""; \
		cat README.md | sed -e 's|docs/assets/|/assets/|g' -e 's|](docs/|](/|g'; \
	} > docs/index.md
	@echo "  >  Index page generation complete!"

gendocs: genopenapi
	@echo "  >  Generating markdown from OpenAPI ..."
	@cd cmd/openapi2md && go run . -input ../../openapi.yaml -output ../../spec
	@echo "  >  Copying schema.md to docs/ for website ..."
	@{ \
		echo "---"; \
		echo "layout: default"; \
		echo "title: Schema Documentation"; \
		echo "nav-title: Schema"; \
		echo "note: This file is automatically generated from the OpenAPI schema. Do not edit this file directly."; \
		echo "---"; \
		echo ""; \
		cat spec/schema.md; \
	} > docs/schema.md
	@echo "  >  Documentation generation complete!"

genpdf: gendocs
	@echo "  >  Generating PDF from markdown documentation ..."
	@if ! command -v pandoc >/dev/null 2>&1; then \
		echo "ERROR: pandoc not found. Install pandoc to generate PDF."; \
		echo "  macOS: brew install pandoc"; \
		echo "  Linux: apt-get install pandoc or yum install pandoc"; \
		exit 1; \
	fi
	@VERSION=$$(cat VERSION 2>/dev/null | sed 's/^/v/'); \
	PDF_ENGINE=""; \
	if command -v pdflatex >/dev/null 2>&1; then \
		PDF_ENGINE="pdflatex"; \
	elif command -v xelatex >/dev/null 2>&1; then \
		PDF_ENGINE="xelatex"; \
	elif command -v lualatex >/dev/null 2>&1; then \
		PDF_ENGINE="lualatex"; \
	elif command -v wkhtmltopdf >/dev/null 2>&1; then \
		PDF_ENGINE="wkhtmltopdf"; \
	elif command -v weasyprint >/dev/null 2>&1; then \
		PDF_ENGINE="weasyprint"; \
	fi; \
	if [ -z "$$PDF_ENGINE" ]; then \
		echo "  >  No PDF engine found (pdflatex, xelatex, lualatex, wkhtmltopdf, or weasyprint)."; \
		echo "  >  Generating HTML instead (convert to PDF manually)..."; \
		cd spec && pandoc schema.md \
			--from markdown \
			--to html \
			--standalone \
			--toc \
			--toc-depth=3 \
			--css=https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown.min.css \
			--metadata title="Security Insights Specification" \
			--metadata author="OpenSSF" \
			--metadata date="$$(date +%Y-%m-%d)" \
			--output ../Security-Insights-$$VERSION.html; \
		echo "  >  HTML generated at Security-Insights-$$VERSION.html"; \
		echo "  >  To generate PDF, install a PDF engine:"; \
		echo "     macOS: brew install basictex (for pdflatex/xelatex/lualatex)"; \
		echo "     macOS: brew install wkhtmltopdf (for wkhtmltopdf)"; \
		echo "     Linux: apt-get install texlive (for pdflatex/xelatex/lualatex)"; \
	else \
		echo "  >  Using PDF engine: $$PDF_ENGINE"; \
		cd spec && pandoc schema.md \
			--from markdown \
			--to pdf \
			--output ../Security-Insights-$$VERSION.pdf \
			--toc \
			--toc-depth=3 \
			--pdf-engine=$$PDF_ENGINE \
			-V geometry:margin=1in \
			-V documentclass=article \
			-V fontsize=11pt \
			--metadata title="Security Insights Specification" \
			--metadata author="OpenSSF" \
			--metadata date="$$(date +%Y-%m-%d)" 2>&1 | grep -v "LaTeX Warning" || \
		(echo "  >  PDF generation with $$PDF_ENGINE failed. Trying HTML fallback..." && \
		 pandoc schema.md \
			--from markdown \
			--to html \
			--standalone \
			--toc \
			--toc-depth=3 \
			--css=https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown.min.css \
			--metadata title="Security Insights Specification" \
			--metadata author="OpenSSF" \
			--metadata date="$$(date +%Y-%m-%d)" \
			--output ../Security-Insights-$$VERSION.html && \
		 echo "  >  HTML generated at Security-Insights-$$VERSION.html (convert to PDF manually)" && \
		 echo "  >  Install LaTeX for better PDF generation: brew install basictex (macOS) or texlive (Linux)"); \
	fi
	@echo "  >  PDF generation complete!"

start: genindex gendocs run

run:
	@echo "  >  Starting Jekyll site ..."
	@if ! command -v ruby -v >/dev/null 2>&1; then \
		echo "ERROR: ruby not found. Install ruby to run the site."; \
		exit 1; \
	fi
	@if ! command -v bundle >/dev/null 2>&1; then \
		echo "ERROR: bundle not found. Install bundler to run the site."; \
		echo "  macOS: gem install bundler"; \
		echo "  Linux: gem install bundler"; \
		exit 1; \
	fi
	@		cd docs && \
		echo "  >  Installing Jekyll dependencies ..."; \
		bundle install; \
		echo "  >  Starting Jekyll server at http://localhost:4000 ..."; \
		bundle exec jekyll serve --host 0.0.0.0

mod-tidy:
	@echo "  >  Tidying CUE module dependencies ..."
	@cue mod tidy
	@echo "  >  Module dependencies tidied!"

mod-resolve:
	@echo "  >  Resolving module path ..."
	@cue mod resolve github.com/ossf/security-insights

mod-publish:
	@echo "  >  Publishing CUE module ..."
	@echo "  >  Note: Publishing requires authentication to the registry."
	@echo "  >  The module will be published to: registry.cue.works/github.com/ossf/security-insights"
	@echo "  >  Version will be determined from git tags (e.g., v2.2.0)"
	@echo ""
	@read -p "  >  Continue with publish? [y/N] " confirm && [ "$$confirm" = "y" ] || exit 1
	@VERSION=$$(cat VERSION 2>/dev/null | sed 's/^/v/'); \
	if [ -z "$$VERSION" ]; then \
		echo "  >  ERROR: Could not determine version from VERSION file"; \
		exit 1; \
	fi; \
	echo "  >  Publishing version $$VERSION ..."; \
	cue mod publish --version $$VERSION

PHONY: lintcue lintyml cuegen genopenapi genindex gendocs genpdf start run mod-tidy mod-resolve mod-publish
