---
name: CI Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Cue
        uses: cue-lang/setup-cue@v1.0.1

      - name: Validate schema.cue
        run: make lintcue

      - name: Validate example files against schema
        run: make lintyml
